[package]
name = "CAIE_Code"
version = "0.1.3"
edition = "2021"
description = "An Interpreter for CAIE Pseudocode"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
sysinfo = "0.29.10"
