name: 问题报告
description: "如果你想反馈 Bug，请使用此模板。"
labels: ["漏洞"]
body:
  - type: markdown
    attributes:
      value: |
        发Issue前请先看看[Issue列表](https://github.com/iewnfod/CAIE_Code/issues)里有没有你的问题，包括已关闭的问题。如有，请关注相关Issue而不是重复发问。
        如果你不确定你遇到的问题是本项目造成的还是你自己操作的失误，请先在[讨论·Discussions](https://github.com/iewnfod/CAIE_Code/discussions)提出。
        请在标题栏中用最简练的语言清晰的描述你遇到的问题。
        标题和内容不必加敬词，所有人都是平等的。
        请在标题内用一句话描述你遇到的问题，勿增加如“帮帮我”、“急急急”、“大神”之类的无意义词汇。
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 在下方的编辑框描述你的问题
      placeholder: 请尽可能说明你遇到的问题
    validations:
      required: true
  - type: textarea
    id: recurrent
    attributes:
      label: 复现方法
      description: 在下方的编辑框描述如何触发这个漏洞（最好直接是需要用到的代码）
      placeholder: 能看到这个？说明你没有看描述，请自己加上“1. ”
      value: "1. "
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: 你的代码
      description: 你可以把你的代码复制到这里
      placeholder: |
        请直接复制你的代码，避免缩进问题
    id: version
    attributes:
      label: 版本信息
      description: 填写你正在使用的CPC版本
      placeholder: 终端输入`cpc -v`查看
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: 额外说明
      description: 还有什么要补充的吗？
      placeholder: |
        提示：
        你还可以提供截图和文件

